### ISSUE TITLE
mitochondrial genes missing

### ISSUE THREAD

**Issue by jan-glx** [maehrlab/de_screen_analysis#1]
In  [GSM3630200](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3630200) and GSM3630201, mitochondrial genes appear to be missing. Is this correct?

**Comment by ekernf01** [comment]
Hi @jan-glx , 

Yes, that is correct -- I just looked back at our custom reference genome, and the mitochondrial genes are not included. That was an unfortunate oversight on my part.

Eric

**Comment by jan-glx** [comment]
Thank you for the quick response!
